### ISSUE TITLE
clarify multi entry vs devServer in react-ts

### ISSUE THREAD

**Issue by DoubleU23** [viewar/webpack#140]
why we have to add this devserver entries,  
and don't use it like react-js/common?

there is also no entry option in react-ts/common

is there a reason for it or just another style?

**Comment by kh-viewar** [comment]
I don't know what exactly you mean. Can you give me a hint to which code you are referring?

In general we had an existing webpack config for typescript, I more or less just copied it over to @viewar/webpack. Never change a running system ;-)

**Comment by DoubleU23** [comment]
webpack config for typescript will not longer be needed
see PR#141 - tested on react-base (with npm link)

will remove the react-ts type ASAP (#142)
